### ISSUE TITLE
avatar jumps over room entrances in field

### ISSUE THREAD

**Issue by hobg0blin** [open-eyebeam/client#33]
doesn't always happen, but have noticed occasionally

**Comment by pwrstudio** [comment]
I have not experienced this. Is it still an issue on your side? Do you have any more context for when it happens?

**Comment by brondle** [comment]
> I have not experienced this. Is it still an issue on your side? Do you have any more context for when it happens?

Doesn't seem to be happening after the latest updates - I wasn't able to figure out what was causing it, it just happened intermittently on a fresh load.
