### ISSUE TITLE
Separate stream setup

### ISSUE THREAD

**Issue by hobg0blin** [open-eyebeam/client#45]
Need an easy way to toggle between ASL interpreter in Zoom and regular streams. This might just be a Zoom setup thing and not require code, but I'm putting it here.

**Also**

Showing multiple videos

**Comment by bingnaa** [comment]
https://www.figma.com/file/3dZLgsteV17NyURZdmz0Qy/Open.Eyebeam---Initial-Experiment?type=design&node-id=0%3A1&t=FwOc7p1mrUQsq5c9-1



![Image](https://github.com/open-eyebeam/client/assets/115378045/cfeab068-0e70-4a9b-9da4-745b4488d68c)
![Image](https://github.com/open-eyebeam/client/assets/115378045/fbe7af56-af43-428c-8551-365535588a70)
![Image](https://github.com/open-eyebeam/client/assets/115378045/dd7f62ae-4285-4188-8424-7644f96f5d93)
![Image](https://github.com/open-eyebeam/client/assets/115378045/a7e9ae09-1b7c-4c32-b795-73a400b1a93b)

**Comment by hobg0blin** [comment]
- Events in "schedule" should launch livestream, maybe an info link.
- Switching between videos requires JS functionality to play/pause the videos as they're replaced - might be best to remove element entirely if it's not playing?
- Is it better to have stream menu under videos, or below schedule?

**Comment by hobg0blin** [comment]
semi-complete, needs debugging
